//// PROPS CONSTANTS ////
export const HASH_LINK = "#";
export const LOWER_TARGET_BLANK = "_blank";
export const LOWER_SUBMIT = "submit";
export const COLOR_BLACK = "#000";
export const LOWER_COLOR_WHITE = "#fff";
export const LOWER_CENTER = "center";
export const LOWER_BODY_ONE = "body1";
export const LOWER_BASIC = "basic";
export const INITIAL_VALUES = { remember: true }
export const LOWER_OFF = "off"
export const LOWER_EMAIL = "email"
export const CAMEL_ON_BLUR = "onBlur"
export const LOWER_LABLE_BETWEEN_MIN_MAX = "${label} must be between ${min} and ${max}"
export const CAP_USER_NAME = "Username"
export const LOWER_USER_NAME = "username"
export const LOWER_DARK = "dark"
export const LOWER_LIGHT = "light"
export const LOWER_TRANSPARENT = "transparent"
export const LOWER_PASSWORD = 'password'
export const CAP_PASSWORD = 'Password'
export const LOWER_TEXT = "text"
export const LOWER_HORIZONTAL = "horizontal"
export const LOWER_VERTICAL = "vertical"
export const LOWER_CHECKED = "checked"
 

//// TEXT CONSTANTS ////
export const CAP_SUBMIT = "Submit";
export const CAP_ABOUT = "About";
export const LOWER_NONE = "none";
export const LOWER_BOLD = "bold";
export const UPPER_OUR_POLICIES = "OUR POLICIES";
export const CAP_LOGO = "Logo"
export const LOWER_NOT_VALID = "is not a valid"
export const LOWER_IS_REQUIRED = "is required"
export const LOWER_LABLE_REQUIRED = "${label} " + LOWER_IS_REQUIRED;
export const LOWER_LABEL_NOT_VALID = "${label} " + LOWER_NOT_VALID
export const CAP_EMAIL = "Email"
export const LOWER_NUMBER = "number"
export const LOWER_TEXT_AREA = "textarea"
export const CAP_LOGIN = "Login"
export const UPPER_O_BET = "OBET"
export const LOWER_ERROR = "error"
export const LOWER_TOKEN = "token"
export const CAP_CREATE = "Create";
export const CAP_NEW = "New";
export const CAP_USER = "User";
export const CAP_CREATE_NEW = CAP_CREATE + " " + CAP_NEW
export const CAP_SHARE = "Share"
export const LOWER_SHARE = "share"
export const LOWER_BETTOR = "bettor"
export const CAMEL_SUPER_MASTER = "superMaster"
export const CAP_TYPE = "Type"
export const LOWER_TYPE = "type"
export const CAP_PHONE = "Phone"
export const LOWER_PHONE = "phone"
export const CAP_NOTES = "Notes"
export const LOWER_NOTES = "notes"
export const CAP_BALANCE = "Balance"
export const LOWER_BALANCE = "balance"
export const LOWER_MUST_BE_GREATER_THAN = "must be greater than"
export const LOWER_MUST_BE_LESS_THAN = "must be less than"
export const CAMEL_USER_TYPE = "userType"
export const CAP_ACCOUNT = "Accounts"
export const CAP_COMMISSION = "Commission"
export const CAP_COMPANY = "Company"
export const CAP_SUPER_ADMIN = "Super Admin"
export const CAP_ADMIN = "Admin"
export const CAP_SUPER_MASTER = "Super Master"
export const CAP_MASTER = "Master"
export const CAP_BETTOR = "Bettor"
export const NUM_STR_0 = "0"
export const NUM_STR_1 = "1"
export const NUM_STR_2 = "2"
export const NUM_STR_3 = "3"
export const NUM_STR_4 = "4"
export const NUM_STR_5 = "5"



